const ROUTES: Record<string, string> = {
  HOME: '/',
  CATALOG: '/catalog',
  SPECIAL_OFFERS: '/catalog/special-offers',
  SUPPLIERS: '/catalog/suppliers',
  WAREHOUSE: '/catalog/warehouse',
  REAGENTS_STANDARTS: '/catalog/reagents-standarts',
  CLINIC_DIAGNISTICS: '/catalog/clinic-diagnostics',
  BIOCHEMISTRY_BIOTECHNOLOGY: '/catalog/biochemistry-biotechnology',
  COSMECEUTICALS: '/catalog/cosmeceuticals',
  ANALYTICAL_EQUIPMENT: '/catalog/analytical-equipment',
  LAB_EQUIPMENT: '/catalog/lab-equipment',
  LIFE_SCIENCES_EQUIPMENT: '/catalog/life-science-equipment',
  CONSUMABLES: '/catalog/consumables',
  PHARMACEUTICALS: '/catalog/pharmaceuticals',
  VETERINARY: '/catalog/veterinary',
  MICROELECTRONICS: '/catalog/microelectronics',
  DELIVERY: '/delivery',
  ABOUT: '/about',
  CONTACTS: '/contacts',
  SHOPPING_CART: '/shopping-cart',
  CHECKOUT: '/checkout',
  PRODUCTS_SEARCH: '/catalog/products-search',
} as const;

export { ROUTES };
