enum Category {
  ANALYTICAL_EQUIPMENT,
  BIOCHEMISTRY_BIOTECHNOLOGY,
  CLINIC_DIAGNOSTICS,
  CONSUMABLES,
  COSMECEUTICALS,
  LAB_EQUIPMENT,
  LIFE_SCIENCE_EQUIPMENT,
  MICROELECTRONICS,
  PHARMACEUTICALS,
  REAGENTS_STANDARTS,
  SPECIAL_OFFERS,
  SUPPLIERS,
  VETERINARY,
  WAREHOUSE,
}

export { Category };
